window.ACTU = [
{y:2024,items:[
{t:"Interview à propos de YU Xuanji",m:"Mai",img:"2023/09/Dans-le-souffle-du-sabre.jpg",body:"Interview sur Radio FM+ à propos de YU Xuanji.",link:"http://media.blubrry.com/radiofmplus/podcast-radiofmplus.org/emissions-culturelles/jardin-isis/2024/JARDIN-D-ISIS-16-MAI.mp3",cta:"Écouter l’interview"},
{t:"Lettre à Orwell",m:"Avril",img:"2024/05/identifiants619.jpg",body:"Lettre à Orwell et échange.",extra:["2024/05/identifiants618-rotated.jpg"]},
{t:"Printemps des poètes",m:"Mars",img:"2024/05/identifiants603.jpg",body:"Printemps des poètes."},
{t:"Lecture de poèmes des femmes afghanes",m:"Février",img:"2024/05/425578629_25178953361689978_9189175105990011655_n.jpg",body:"Lecture de poèmes des femmes afghanes au Gazette Café.",wide:true}]},
{y:2023,items:[
{t:"Lecture « Dans le souffle du sabre »",m:"",img:"2023/12/Anne-Marie-a-latelier-de-shanshan-sun.png",body:"Lecture-présentation de YU Xuanji, Dans le souffle du sabre – atelier de Shanshan Sun, avec exposition en hommage à Yu Xuanji."},
{t:"Exposition à la bibliothèque d’Aniane",m:"",img:"2023/12/csm_Aniane_7b0da9dfa3.jpg",body:"Exposition Bibliothèque d’Aniane – café-lecture.",wide:true},
{t:"Présentation de Yu Xuanji",m:"Septembre",img:"2023/12/Maison-de-la-poesie.jpg",body:"Brève présentation de l’ouvrage Yu Xuanji à la Maison de la Poésie.",wide:true},
{t:"Bibliothèque de Vendémian",m:"",img:"2023/12/identifiants492.jpg",body:"Présentation d’Akhmatova avant lecture de ses poèmes par l’équipe du TPVH."},
{t:"Biennale de la poésie visuelle",m:"Mai",body:"2 collages à la Biennale de poésie visuelle – Ille-sur-Têt – dirigée par André Robèr. Magazine Nuire #11.",img:"2023/12/nuire-n°-11.jpg"},
{t:"Printemps des poètes",m:"",img:"2023/12/pj522_2008-logo-pdp-coul.jpg",body:"Deux interventions durant le Printemps des Poètes à La Boissière.\nSalle Laure Moulin – Chemins singuliers – lecture en compagnie de Chantal Enocq et Marie-Agnès Salehzada.\nSalle Laure Moulin – Présentation d’Akhmatova avant lecture de ses poèmes par l’équipe du TPVH."},
{t:"Le meilleur des mondes",m:"Mars",img:"2023/12/Affiche-AMJ-mars-2023-1.jpg",body:"Invitée à la librairie « Le meilleur des mondes » à Aniane. Lecture des dernières parutions AMJ avec Manouchka Poincignon."},
{t:"Festival Les Mots Parleurs",m:"Février",img:"2023/12/Akhm-1.jpg",body:"Festival Les Mots Parleurs à la Bibliothèque de Bélarga. Présentation d’Akhmatova avant lecture de ses poèmes par l’équipe du TPVH."},
{t:"Les jardins d’Isis",m:"Janvier",img:"2023/12/Jardins-dIsis.jpg",body:"Invitée sur FM+ pour le podcast Jardin d’Isis par Marie-Agnès Salehzada. Émission consacrée au landaï, poésie orale peu connue des femmes d’Afghanistan.",link:"http://media.blubrry.com/radiofmplus/podcast-radiofmplus.org/emissions-culturelles/jardin-isis/2023/JARDIN-ISIS-05-JANVIER.mp3",cta:"Écouter l’émission"}]},
{y:2022,items:[
{t:"Participe à Busta Sorpresa n°43",m:"",img:"2023/09/identifiants544.jpg",body:"Invitée par Carla Bertola – Turin, Italie."},
{t:"Invitée au Festival Les Eauditives",m:"",img:"2023/09/identifiants333.jpg",body:"Invitée au Festival pour la parution de Casse-tête.",extra:["2023/09/identifiants334.jpg"]},
{t:"Chemins singuliers",m:"",img:"2023/09/Chemins-singuliers-flyer.png",body:"Invitation dans son jardin de Claret par Didier St Jean pour une lecture à trois auteures."},
{t:"Inconscient et réverbérations poétiques",m:"",img:"2023/09/Inconscient-et-reverberations-poetiques-n.jpg",body:"Invitée par Luminitza Tigirlas au Gazette Café."}]},
{y:2020,items:[
{t:"Invitation par la Maison de la poésie Jean Joubert",m:"Mars",img:"2023/09/identifiant646.jpg",body:"Anne-Marie Jeanjean à la Médiathèque centrale Émile Zola, Montpellier, mardi 10 mars 2020.",link:"https://www.autourdesauteurs.fr/2020/03/08/anne-marie-jeanjean-a-la-mediatheque-centrale-emile-zola-montpellier-mardi-10-mars-2020/",cta:"Autour des auteurs"}]},
{y:2019,items:[
{t:"Couverture « Notre époque »",m:"",img:"2023/08/Couverture-Oeuvre-collective-1.jpg",body:"Cette histoire s’écrit encore…"},
{t:"Musée de Tuin",m:"",img:"2023/09/identifiants542-1.jpg",body:"Cette histoire s’écrit encore…"},
{t:"Couverture Teste 34",m:"",img:"2023/09/identifiants541-2.jpg",body:"Cette histoire s’écrit encore…\n\nPoète, artiste-auteure inclassable, Anne-Marie Jeanjean nous entraîne dans sa démarche originale, à la découverte de son travail sans cesse expérimental, nourri des rencontres que les textes anciens, classiques ou d’avant-garde lui apportent."}]},
{y:2018,items:[
{t:"Anne-Marie Jeanjean parle de ses livres",m:"",img:"2023/08/Lecture.jpg",wide:true,body:"Pour le magnifique catalogue Peinture et poésie – Les peintres vus par les poètes – et sur proposition de Maïté Vallès-Bled, conservateur en chef du patrimoine et directrice du musée Paul Valéry, A.M. Jeanjean avait choisi le tableau Joutes sétoises (1950) de François Desnoyer.\n\nSa lecture au Musée Paul Valéry comprenait ce poème ainsi que l’évocation des liens très étroits qu’elle entretient avec la peinture depuis toujours et qui se retrouvent dans bien de ses ouvrages.\n\n« Les peintres vus par les poètes » permet en effet un va-et-vient fructueux du tableau au poème et du poème au tableau : impressions, lectures, déchiffrages différents selon les points de vue, aiguisent le regard et la réflexion. Une joie que tout lecteur du catalogue ou visiteur du Musée pourra ressentir !",link:"http://museepaulvalery-sete.fr/",cta:"museepaulvalery-sete.fr"},
{t:"Poésie à deux voix",m:"17 mars",img:"2023/08/act2.jpg",wide:true,body:"Samedi 17 mars 2018 à l’espace Castel de Lunel. Anne-Marie Jeanjean lit ses poèmes à deux voix à l’invitation de Martine Biard à l’occasion du Printemps des poètes 2018."},
{t:"Carte blanche, Maison de la poésie",m:"",img:"2023/08/Carte-blanche.jpg",body:"Carte blanche à Anne-Marie Jeanjean. Maison de la poésie Jean Joubert.\n\nPoète, artiste-auteure inclassable, Anne-Marie Jeanjean nous entraîne dans sa démarche originale, à la découverte de son travail sans cesse expérimental, nourri des rencontres que les textes anciens, classiques ou d’avant-garde lui apportent."}]},
{y:2017,items:[
{t:"Ainsi chantait Miss Drac’Ula",m:"",img:"2023/09/Ainsi-chantait-miss-dracula.jpg",body:"« Il y a de l’épique dans ce texte aux vers vertigineux. Et du sonore vociféré (…) et du visuel aussi, autant de traces en surimpression » écrit Alain Hélissen en 4ème de couverture.\n\nMais qui est donc ce mystérieux personnage, cette surprenante Miss Drac’Ula qui s’installe chez la narratrice sans façon… bousculant passé-présent et quotidien rassurants !? Et… jusqu’où la mènera-t-elle ?\n\nCritique de Jean-Paul Gavard-Perret sur lelitteraire.com.",link:"http://www.lelitteraire.com/?p=22821",cta:"Lire la critique"},
{t:"Comédie du livre 2017",m:"",img:"2023/09/lecture-comedie-du-livre-2017.jpg",body:"Lecture à la 32e Comédie du livre à Montpellier."},
{t:"Plasticiens ès Lettres – Open Space, Sète",m:"",img:"2023/09/anne-marie-jeanjean-alain-robinet-open-space-sete.png",body:"Alain Robinet – Anne-Marie Jeanjean, poètes ? Écrivains ? Plasticiens ès Lettres !\n\nDès ses débuts, Alain Robinet écrit, bouscule, écorne la langue vaillamment ; Anne-Marie Jeanjean écrit depuis longtemps mais commence à découvrir l’écriture avec colle et ciseaux, pour l’écorcher, lui faire violence, la sommer d’en dire + que les convenances. De leurs premiers contacts il y a quelques dizaines d’années s’opère sur ce socle une connivence discrète mais certaine qui produira un livre en 1979 : « Fréquence 243… mcs », coll. Textuerre, où se tissent déjà dactylo & calligraphies…\n\nLes détours de la vie les feront se perdre de vue, années pendant lesquelles Alain Robinet publie/peint sans arrêt tandis qu’Anne-Marie Jeanjean déchire ses textes, explore les différentes techniques du collage, et ce qui se joue autour de la lettre et du signe. La reprise de leur dialogue, proximité géographique aidant, se produit à travers ce fil conducteur commun : la passion questionnante de la plasticité du signe & ses polysémies possibles par froissages, encres, écrits pour décrire l’espace de la Lettre d’être homo stylo, homo pinço depuis Lascaux & co !"}]},
{y:2016,items:[
{t:"Exposition Tuto",m:"Décembre",img:"2023/09/exposition-tuto.jpg",body:"TUTO, célèbre peintre chinois dit « extravagant », a créé en 2010 ce petit personnage désormais très connu. Exposition de TUTO pendant le mois de décembre.\n\nCharmant\npetit personnage\ndans l’étoilement céleste\ncharmant comme dans un conte ou une fable\n\nMAIS il faut accepter de VOIR\nVOIR que la pointe du croissant\njuste au niveau du cœur et de part en part\na embroché ce petit humain\n\nRêves\nIllusions\nNostalgies\nTOUT a été congédié\n\nAMJ, décembre 2016"},
{t:"Anthologie Voix Vives, Sète 2016",m:"",img:"2023/09/anthologie-sete-2016.jpg",wide:true,body:"Poème publié dans l’anthologie du festival."},
{t:"Voix Vives en Méditerranée",m:"",img:"2023/09/voixvivesmediterranee.jpg",body:"Invitée au Festival Voix Vives en Méditerranée, lecture de poèmes."},
{t:"Entretien avec A.-M. Jeanjean",m:"",img:"2023/08/Portrait-cal-AMJ.jpg",body:"La femme du Lac et le chant de la langue : entretien avec Anne-Marie Jeanjean (Ainsi chantait Miss Drac’Ula).\n\nQu’est-ce qui vous fait lever le matin ? — La saveur d’un thé de Chine.\n\nQue sont devenus vos rêves d’enfant ? — Ils se réalisent : je lis (presque) ce que je veux / j’écris avec plume, colle et ciseaux ou tout instrument traditionnel ou bizarre.",link:"http://www.lelitteraire.com/?p=22846",cta:"Découvrir cette rencontre"},
{t:"Du poème à l’écriture visuelle",m:"18 février",img:"2023/09/du-poeme-a-l-ecriture-visuelle.png",body:"Lycée Louis Feuillade à Lunel, 18 février 2016. Bernard Teulon-Nouailles, dans le cadre de son programme littérature, présente : Du poème à l’écriture visuelle, avec la poète invitée Anne-Marie Jeanjean."},
{t:"Krochka, encres et dessins",m:"",img:"2023/09/krochka-encres-et-dessins.png",body:"Krochka est peintre. Certes, et pas seulement. Depuis 1995 elle expose des travaux d’un autre ordre, d’une autre nature… Avec un succès constant car ces « graphismes singuliers » suscitent mille interprétations et projections.\n\nN’est-il pas grand temps d’interroger cette pratique étonnante ? C’est ce que tente de proposer ce court ouvrage avec des points de vue subjectifs d’auteurs venant d’horizons différents."}]},
{y:2015,items:[
{t:"Revue Étoiles d’encre",m:"",img:"2023/09/etoile-d-encre.jpg",body:"La revue Étoiles d’Encre consacre son n°63-64 à la question « Sommes-nous folles ? » avec au sommaire plus d’une quarantaine d’auteures. Un dossier nous révèle l’œuvre de Danielle Maffray dont les illustrations couleur rythment l’ouvrage. Un forum et d’autres rubriques trouvent place dans ce riche numéro."},
{t:"Prix international du poète résistant",m:"2 octobre",img:"2023/09/le-grand-massacre.jpg",body:"Le prix international du poète résistant est attribué à LIAO YIWU pour son ouvrage Poèmes de prison (Éd. L’Harmattan), traduit pour la première fois en Occident par Sh. Sun et A.M. Jeanjean.\n\n2 oct. – 17 h – Festival du Livre. A.M. Jeanjean y parle de la traduction et lit quelques poèmes."},
{t:"Dialogues d’imaginaires",m:"Septembre",img:"2023/09/dialogues-d-imaginaires.jpg",body:"Dialogues d’imaginaires au Centre Européen de poésie d’Avignon avec Anne-Marie Jeanjean et Inès Wickmann. 1er au 30 septembre 2015.\n\nLecture-rencontre : 12 septembre 2015, 17h–19h. Vernissage de l’exposition : 12 septembre 2015 à 19h.",link:"http://www.iwickmann.com/",cta:"iwickmann.com"},
{t:"L’Empire du Sens",m:"Juillet",img:"2023/09/empire-du-sens.jpg",body:"Stéphane Bernard a le plaisir de vous inviter au vernissage de son exposition de sculptures « L’Empire du Sens », au jardin de la Frigoule le vendredi 31 juillet à partir de 17h30. Une vingtaine de pièces en châtaignier : un parcours choisi à travers 28 ans de création cévenole et contemporaine.\n\nExposition du 14 juillet au 31 août 2015 – TLJ 10h–21h. Permanence du sculpteur 10h–13h du mardi au samedi."},
{t:"Muse toi-même !",m:"",img:"2023/09/muse.jpg",body:"Anthologie arbitraire de poésie féminine au XXIe siècle. Nadine Agostini, Edith Azam, Pauline Catherinot, Anne-Marie Jeanjean, Emmanuelle K., Claudie Lenzi, Alice Popieul. Textes choisis et présentés par Guilhem Fabre. Le Bateau Ivre, 2015, collection Ocre Mer – ISBN 979-1092622119.",link:"http://lebateauivre.fr/",cta:"Éditions Le Bateau Ivre"}]},
{y:2013,items:[
{t:"Décès de Georges Baal",m:"",img:"2023/09/kultura_Elhunyt-Georges-Baal-magyar-szarmazasu-pszichoanalitikus-szinhazi-szakember_nagy.jpg",body:"Comédien, il a d’abord l’esprit d’un « chercheur-né », d’un questionneur…\n\nArrivé en France en 1956, il se consacre à la biologie moléculaire, puis à la génétique. De là il passe à la psychologie, à la psychanalyse et aux différents courants du théâtre tout en s’intéressant passionnément à la littérature d’avant-garde de son pays, la Hongrie, et de la France.\n\nFinalement ses connaissances de psychanalyste vont nourrir ses réflexions d’homme de théâtre, aussi élabore-t-il un théâtre expérimental tout à fait singulier, l’une de ses sources étant ce qu’on appelait le théâtre pauvre. À partir de ce théâtre expérimental il met au point sa méthode Théâtre et Thérapie et se spécialise dans le domaine de l’addiction à la drogue : il fera pendant des années de nombreux ateliers en Europe et notamment en Hongrie.\n\nSon intérêt pour l’écriture, les avant-gardes littéraires a été constant et sans doute quelques spectateurs se rappellent-ils encore des spectacles bouleversants réalisés d’après des textes qui n’étaient pas a priori destinés au théâtre comme Lautréamont, Artaud… tout au long des années 80.\n\nC’est alors qu’il devient l’interlocuteur privilégié concernant mon questionnement à propos du théâtre. Plusieurs rencontres seront nécessaires pour finaliser le dossier Texte/corps/théâtre pour le n°23/24 de Textuerre en juin 1980. Il met en scène mon texte Via Scavi (1981-1982) et réalise un montage/performance : Nous t’attendions pour le dépeçage à partir de plusieurs de mes livres. On le retrouve régulièrement dans les numéros de Textuerre : n°31/32 1981 (dossier Via Scavi) – n°57/58 nov. 86 L’acteur dans l’épaisseur de la lettre – n°62 (1988) Trois écrivains du pays magyar – n°64 (1989) L’acteur, un étranger sur la scène – n°66 (1990) À la dérive d’Artaud.\n\nImpossible de retracer en quelques lignes un parcours d’une telle richesse, aussi espérons que ses proches, amis, collègues, artistes d’horizons divers ne manqueront pas de faire écho à son œuvre et… – qui sait ? – dans un futur plus lointain, de poursuivre ses recherches."}]}
];
